server:
  port: 8080

database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  dbname: postgres
  pool:
    min-size: 8
    max-size: 16

configuration-properties:
  send-user-to-olb-scheduler-cron: "* * * * *"
  send-user-to-olb-scheduler-section-advisory-lock: 1